### ISSUE TITLE
Grammar section should be locally scrollable

### ISSUE THREAD

**Issue by jfo** [zig-lang/www.ziglang.org#9]
![jan-28-2018 01-49-12](https://user-images.githubusercontent.com/4204764/35477845-a514b0ee-03cd-11e8-98e7-1e4846732090.gif)

**Comment by tiehuis** [comment]
Think this ties in with general mobile viewports. We need a few styling changes (i.e. smaller font) for better mobile browsing.

**Comment by jfo** [comment]
@tiehuis I agree. I'd _love_ to get a markdown parser going in zig, to make these docs friendlier to both editing locally and viewing in github. Probably conformant to [commonmark](http://commonmark.org/) since that's the closest thing to a markdown spec there is. It would even be easy to continue using hljs for the fenced code blocks in that case! Regexes would be very helpful with that project 😃. I liked [that article](https://swtch.com/~rsc/regexp/regexp1.html) so much that if I have some time I would like to try to implement it too for the learns. Would love to see your work / compare notes at some point.

**Comment by andrewrk** [comment]
#4 introduced this scrolling glitch. idk how the media/screen/viewport stuff works.

I'm not necessarily disagreeing with you, but what does markdown buy us? it's one markup syntax traded for another one, and ultimately we need html. Have you seen what langref.html.in looks like now that it is automatically tested? I ended up adding a custom syntax on top of html to mark up code sections as well as auto generate the TOC. 

now what's left in langref.html.in is the html skeleton we need, css, javascript, `<p>`, `<strong>`, `<em>`, `<a>` for external links only, `<ul>`, `<table>` (way easier in html than markdown) , inline `<code>`.

what does markdown buy us?

I do think we want a markdown parser, probably for the autogenerated code documentation based on `///` comments. I'm not convinced it's an improvement for the language reference.

maybe I'm just a weirdo. if making the docs markdown means that more people will contribute docs, I'm all in.

**Comment by jfo** [comment]
Haha I wouldn't use the term "weirdo", and maybe I'm just a sucker for markdown.

Truth is it doesn't buy us a _lot_, you are right that markup is markup, ultimately. But, markdown when done right is much easier to read, easier to write, easier to contribute to, and functionally equivalent to hmtl (albeit with a compilation step, which I appreciate is a low but non-zero cost).

I'm probably more excited about trying to write a markdown parser than I am about making the docs use markdown, I wouldn't advocate adding more external tooling in order to use it here, but if there were a zig markdown library I would consider it seriously!

As far as `<table>`, sure! you can just use html from within markdown!

**Comment by tiehuis** [comment]
By the way, I had started an initial documentation generator some time ago. I wanted markdown support for those comments so had started an initial parser for it as well. I've left it for the moment since I think there are a few other things more important right now. We can also use the self-hosted compiler when its in a more mature state for the actual tokenization/parsing and don't need to duplicate the work.

https://github.com/tiehuis/zig-docgen

As for converting docs to markdown. I think it's worthwhile in the long term once we have a markdown parser with enough functionality to compile the entire document. As for specifying test cases, we can add some sort of annotation to code blocks easy enough.

Here is an old conversion to markdown. We can just revisit from scratch later since it wasn't the time-intensive to convert the document.

https://github.com/zig-lang/www.ziglang.org/pull/2
